# dsh-desktop-release 一键安装脚本
# 用法：cd dsh-desktop-release; ./install.ps1
# 功能：安装 3 个插件到 DSH web profile + 追加 cordis.patch.yml 条目 + 部署 SKILL.md 技能。
# 依赖：dsh CLI 在 PATH 中；DSH_HOME 默认 %USERPROFILE%\.dsh。

[CmdletBinding()]
param(
    [string]$Profile = "web",
    [string]$DshHome = "",
    [string]$KbRoot = "",
    [string]$WorkspaceRoot = "",
    [switch]$SkipPlugins
)

$ErrorActionPreference = "Stop"

# ---- 定位 DSH_HOME ----------------------------------------------------------
if (-not $DshHome) {
    $DshHome = if ($env:DSH_HOME) { $env:DSH_HOME } else { Join-Path $env:USERPROFILE ".dsh" }
}
$ReleaseDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PluginsDir = Join-Path $ReleaseDir "plugins"
$ProfileDir = Join-Path $DshHome "profiles\$Profile"
$PatchFile = Join-Path $ProfileDir "cordis.patch.yml"
$SkillDestDir = Join-Path $DshHome "skills\dsh-desktop"

Write-Host "==> DSH_HOME   : $DshHome"
Write-Host "==> Profile    : $Profile"
Write-Host "==> ReleaseDir : $ReleaseDir"

# ---- 1. 检查 dsh CLI ----------------------------------------------------------
$dshCmd = Get-Command dsh -ErrorAction SilentlyContinue
if (-not $dshCmd) {
    Write-Error "未找到 dsh 命令。请先安装 DeepSeek Harness（npm i -g @deepseek-ai/dsh），或把 dsh 加入 PATH。"
    exit 1
}

# ---- 2. 安装插件（link 方式）----------------------------------------------------
if ($SkipPlugins) {
    Write-Host "==> 已跳过插件安装（-SkipPlugins）"
} else {
    $pluginNames = @("dsh-desktop-plugin", "dsh-ocr-plugin", "dsh-kb-plugin")
    foreach ($p in $pluginNames) {
        $src = Join-Path $PluginsDir $p
        if (-not (Test-Path $src)) {
            Write-Warning "缺少插件目录：$src（跳过）"
            continue
        }
        Write-Host "==> 安装插件 $p ..."
        $env:DSH_HOME = $DshHome
        & $dshCmd.Source plugin --profile $Profile add $src
        if ($LASTEXITCODE -ne 0) {
            Write-Error "dsh plugin add 失败（退出码 $LASTEXITCODE）：$p"
            exit 1
        }
    }
}

# ---- 3. 追加 cordis.patch.yml 条目（幂等）--------------------------------------
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
if (-not (Test-Path $PatchFile)) {
    Set-Content -Path $PatchFile -Value "# generated by dsh-desktop-release install.ps1" -Encoding UTF8
}
$existing = Get-Content $PatchFile -Raw -Encoding UTF8

$kbConfig = ""
if ($KbRoot) { $kbConfig += ("            kbRoot: '" + $KbRoot + "'`n") }
if ($WorkspaceRoot) { $kbConfig += ("            workspaceRoot: '" + $WorkspaceRoot + "'`n") }

$inserts = @()
if ($existing -notmatch "id:\s*desktop\b") {
    $inserts += @(
        "- insert:"
        "    - id: desktop"
        "      name: 'dsh-desktop'"
        "      config:"
        "        notifyDurationMs: 5000"
        "        openTimeoutMs: 10000"
    ) -join "`n"
}
if ($existing -notmatch "id:\s*ocr\b") {
    $inserts += @(
        "- insert:"
        "    - id: ocr"
        "      name: 'dsh-ocr'"
        "      config:"
        "        lang: zh-Hans-CN"
        "        maxFrames: 6"
    ) -join "`n"
}
if ($existing -notmatch "id:\s*kb\b") {
    $kbLines = @(
        "- insert:"
        "    - id: kb"
        "      name: 'dsh-kb'"
        "      config:"
    )
    if ($KbRoot) { $kbLines += "        kbRoot: '" + $KbRoot + "'" }
    if ($WorkspaceRoot) { $kbLines += "        workspaceRoot: '" + $WorkspaceRoot + "'" }
    $inserts += $kbLines -join "`n"
}
if ($inserts.Count -gt 0) {
    $block = "`n" + ($inserts -join "`n`n") + "`n"
    Add-Content -Path $PatchFile -Value $block -Encoding UTF8
    Write-Host "==> 已追加插件条目到 $PatchFile"
} else {
    Write-Host "==> cordis.patch.yml 已包含所需条目，跳过"
}

# ---- 4. 部署 SKILL.md 技能文档 ---------------------------------------------------
if (Test-Path (Join-Path $ReleaseDir "SKILL.md")) {
    New-Item -ItemType Directory -Force -Path $SkillDestDir | Out-Null
    Copy-Item (Join-Path $ReleaseDir "SKILL.md") (Join-Path $SkillDestDir "SKILL.md") -Force
    Write-Host "==> 已部署技能文档到 $SkillDestDir"
} else {
    Write-Warning "发布包根目录缺少 SKILL.md，技能未部署"
}

# ---- 5. 完成 -------------------------------------------------------------------
Write-Host ""
Write-Host "安装完成！请重启 dsh 生效：dsh web"
Write-Host "验证：新开会话，对智能体说「用 desktop_status 看环境，再用 desktop_notify 发条通知」。"
